### ISSUE TITLE
Update Travis file

### ISSUE THREAD

**Issue by t-fine** [open-horizon/examples#417]
Travis is currently failing to install the hzn cli. We need to update the old mentor of installing the cli
```
# Install the hzn command
addons:
  apt:
    update: true
    sources:
    - sourceline: deb [arch=amd64,armhf,arm64] http://pkg.bluehorizon.network/linux/ubuntu bionic-updates main
      key_url: 'http://pkg.bluehorizon.network/bluehorizon.network-public.key'
    packages:
    - horizon-cli
```

to grab from the anax releases https://github.com/open-horizon/anax/releases
